[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
remappings = [
    "@openzeppelin/contracts/=dependencies/openzeppelin-contracts/contracts/",
    "forge-std/=dependencies/forge-std/src/"
]
solc = "0.8.18"
optimizer = true
optimizer_runs = 200
test = "test"            # Explicitly set test directory
test_pattern = "*.t.sol" # Match all test files
auto_detect_solc = false
fuzz = { runs = 1_000 }
bytecode_hash = "none"
gas_reports = ["*"]
evm_version = "paris"

# Removed remappings section to avoid conflict with Soldeer-managed remappings.txt

[profile.default.sdependencies]
forge-std = "1.7.6"
openzeppelin-contracts = "4.8.0"
optimism = "1.7.0"
nitro-contracts = "1.7.0"
token-bridge-contracts = "1.7.0"
zksync-contracts = "1.7.0"
scroll-contracts = "latest"
smartcontractkit-chainlink-brownie-contracts = "1.3.0"
cyfrin-foundry-devops = "0.4.0rc"

[soldeer]
# whether soldeer manages remappings
remappings_generate = false
# whether soldeer re-generates all remappings when installing, updating or uninstalling deps
remappings_regenerate = false
# whether to suffix the remapping with the version: `name-a.b.c`
remappings_version = false
# a prefix to add to the remappings ("@" would give `@name`)
remappings_prefix = "@"
# where to store the remappings ("txt" for `remappings.txt` or "config" for `foundry.toml`)
# ignored when `soldeer.toml` is used as config (uses `remappings.txt`)
remappings_location = "txt"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
blockdag = "${BLOCKDAG_RPC_URL}"
celo = "${CELO_RPC_URL}"
base = "${BASE_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"

[dependencies]
forge-std = "1.7.6"
openzeppelin-contracts = "4.8.0"

[etherscan]
blockdag = { key = "${BLOCKDAG_API_KEY}" }
celo = { key = "${CELO_API_KEY}" }
base = { key = "${BASE_API_KEY}" }
arbitrum = { key = "${ARBITRUM_API_KEY}" }
