[profile.default]
src = "src"
out = "out"
<<<<<<< HEAD
libs = [ "dependencies"]
test = "test"  # Explicitly set test directory
test_pattern = "*.t.sol"  # Match all test files
auto_detect_solc = false 
fuzz = { runs = 1_000 } 
bytecode_hash = "none" 
gas_reports = ["*"] 
solc_version = "0.8.19"
=======
libs = ["dependencies"]
test = "test"            # Explicitly set test directory
test_pattern = "*.t.sol" # Match all test files
auto_detect_solc = false
fuzz = { runs = 1_000 }
bytecode_hash = "none"
gas_reports = ["*"]
>>>>>>> 47ca159 (Creation of smart contracts)

[dependencies]
forge-std = "1.9.6"
smartcontractkit-chainlink-brownie-contracts = "1.3.0"
cyfrin-foundry-devops = "0.4.0rc"
"@openzeppelin-contracts" = "5.3.0"

[soldeer]
# whether soldeer manages remappings
remappings_generate = true
# whether soldeer re-generates all remappings when installing, updating or uninstalling deps
remappings_regenerate = false
# whether to suffix the remapping with the version: `name-a.b.c`
remappings_version = true
# a prefix to add to the remappings ("@" would give `@name`)
remappings_prefix = ""
# where to store the remappings ("txt" for `remappings.txt` or "config" for `foundry.toml`)
# ignored when `soldeer.toml` is used as config (uses `remappings.txt`)
remappings_location = "txt"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
blockdag-primordial-testnet = "https://rpc.primordial.bdagscan.com"
